Develop
ZimnitskiYury/react-redux-project pull request #1
Opened 2021-06-21 23:42 UTC by ZimnitskiYury

2021-06-29 07:18 UTC, drodov commented on src/app/app.jsx
> +          <Header sidebarHandler={() => toggleSidebar((state) => !state)} />
You can specify just () => toggleSidebar(!state)

2021-06-29 07:43 UTC, drodov requested changes

2021-06-29 07:43 UTC, drodov commented on src/common/components/BurgerButton/burgerButton.jsx
> +export default BurgerMenu;
Please place export default always at the end of file.
ESLint rule: import/exports-last

2021-06-29 07:43 UTC, drodov commented on src/features/favorites/components/ToggleFavoriteButton/toggleFavoriteButton.jsx
> +const classNames = require('classnames');
Please move it to the first group of imports.

2021-06-29 07:43 UTC, drodov commented on src/modules/beer-details-page/components/beerDetailsPage.jsx
> +    [
Please create an empty array at one line.

2021-06-29 07:43 UTC, drodov commented on src/modules/beer-details-page/components/beerDetailsPage.jsx
> +  if (beer) {
It's always better to revert `if` statements in such cases in order to decrease code nesting.

2021-06-29 07:43 UTC, drodov commented on src/modules/favorites-page/components/FavoriteBeer/favoriteBeer.jsx
> +      <div
It should be image tag instead.

2021-06-29 07:43 UTC, drodov commented on src/modules/landing-page/actions/searchBeersActions.js
> +  if (ebc) {
Please put empty lines between `if` to increase readability.

2021-06-29 07:43 UTC, drodov commented on src/modules/landing-page/components/BeerCard/BeerCardOpenButton.jsx
> +import styles from './beerCardOpenButton.css';
Add an empty line before last import.

2021-06-29 07:43 UTC, drodov commented on src/modules/landing-page/components/BeerCard/BeerCardOpenButton.jsx
>  import React from 'react';
Please make sure that each component has its own folder with the name of the component.

2021-06-29 07:43 UTC, drodov commented on src/modules/landing-page/components/BeerCard/beerCard.jsx
> +      <div
Please use img tag.

2021-06-29 07:43 UTC, drodov commented on src/modules/landing-page/components/SearchBox/searchBox.jsx
> +    IsShownFilters,
Do not capitalize the first letter. Also, please fix the grammar, it should be `areFiltersShown`.

2021-06-29 07:43 UTC, drodov commented on src/modules/landing-page/hooks/infiniteLoaderHook.js
> +      if (containerRef.current) observer.observe(containerRef.current);
Please add curly braces.

2021-06-29 07:43 UTC, drodov commented on src/modules/layout/components/Header/header.jsx
> +// @ts-nocheck
Please remove.

2021-06-29 07:43 UTC, drodov commented on src/modules/layout/components/Header/header.jsx
> +        <img
Import icon as in another plaease as a component.

2021-06-29 07:43 UTC, drodov commented on src/modules/layout/components/Sidebar/sidebar.jsx
> +    <div className={isOpen
Use classnames here.

2021-06-29 07:43 UTC, drodov commented on src/services/connectConstants.js
> +export const URL_PUNKAPI = new URL('https://api.punkapi.com/v2/beers');
If you create project-level constants move them to a separate folder `constants`. But here I would move this constant to punkService.js because it is used only there, it's related only to this service.

2021-06-29 23:13 UTC, ZimnitskiYury commented on src/common/components/BurgerButton/burgerButton.jsx
> +export default BurgerMenu;
Added rule

2021-06-29 23:14 UTC, ZimnitskiYury commented on src/modules/beer-details-page/components/beerDetailsPage.jsx
> +    [
Changed rule for array

2021-06-29 23:15 UTC, ZimnitskiYury commented on src/modules/landing-page/components/SearchBox/searchBox.jsx
> +    IsShownFilters,
Fixed

2021-07-01 23:52 UTC, ZimnitskiYury commented on src/app/app.jsx
> +          <Header sidebarHandler={() => toggleSidebar((state) => !state)} />
Fixed

2021-07-01 23:52 UTC, ZimnitskiYury commented on src/features/favorites/components/ToggleFavoriteButton/toggleFavoriteButton.jsx
> +const classNames = require('classnames');
Fixed

2021-07-01 23:53 UTC, ZimnitskiYury commented on src/modules/beer-details-page/components/beerDetailsPage.jsx
> +  if (beer) {
Fixed

2021-07-01 23:56 UTC, ZimnitskiYury commented on src/modules/landing-page/hooks/infiniteLoaderHook.js
> +      if (containerRef.current) observer.observe(containerRef.current);
Fixed

2021-07-01 23:57 UTC, ZimnitskiYury commented on src/modules/layout/components/Header/header.jsx
> +// @ts-nocheck
fixed

2021-07-02 00:00 UTC, ZimnitskiYury commented on src/modules/layout/components/Header/header.jsx
> +        <img
Fixed

2021-07-02 00:01 UTC, ZimnitskiYury commented on src/services/connectConstants.js
> +export const URL_PUNKAPI = new URL('https://api.punkapi.com/v2/beers');
Fixed

2021-07-02 00:02 UTC, ZimnitskiYury commented on src/modules/landing-page/actions/searchBeersActions.js
> +  if (ebc) {
Added rule to eslint config

2021-07-02 00:05 UTC, ZimnitskiYury commented on src/modules/landing-page/components/BeerCard/BeerCardOpenButton.jsx
> +import styles from './beerCardOpenButton.css';
Fixed

2021-07-02 00:05 UTC, ZimnitskiYury commented on src/modules/landing-page/components/BeerCard/BeerCardOpenButton.jsx
>  import React from 'react';
Fixed

2021-07-02 00:31 UTC, ZimnitskiYury commented on src/modules/favorites-page/components/FavoriteBeer/favoriteBeer.jsx
> +      <div
Fixed

2021-07-02 00:38 UTC, ZimnitskiYury commented on src/modules/layout/components/Sidebar/sidebar.jsx
> +    <div className={isOpen
Added

2021-07-22 10:38 UTC, merged